// <auto-generated />
using System;
using DigitalSignEditor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigitalSignEditor.Migrations
{
    [DbContext(typeof(SignContext))]
    partial class SignContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DigitalSignEditor.Data.Models.CalendarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIcs")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CalendarItems");
                });

            modelBuilder.Entity("DigitalSignEditor.Data.Models.Sign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("College")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinimumHeight")
                        .HasColumnType("int");

                    b.Property<int>("MinimumWidth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatioHeight")
                        .HasColumnType("int");

                    b.Property<int>("RatioWidth")
                        .HasColumnType("int");

                    b.Property<int>("SignType")
                        .HasColumnType("int");

                    b.Property<string>("TwitterHandle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Signs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            College = 0,
                            Description = "Sample sign used for testing",
                            IsActive = true,
                            LastUpdated = new DateTime(2022, 3, 17, 11, 35, 43, 705, DateTimeKind.Local).AddTicks(4627),
                            MinimumHeight = 600,
                            MinimumWidth = 800,
                            Name = "Sample Lobby Sign",
                            RatioHeight = 9,
                            RatioWidth = 16,
                            SignType = 0,
                            TwitterHandle = "edILLINOIS",
                            Url = "edlobby"
                        },
                        new
                        {
                            Id = -2,
                            College = 0,
                            Description = "Sample sign used for testing",
                            IsActive = true,
                            LastUpdated = new DateTime(2022, 3, 17, 11, 35, 43, 708, DateTimeKind.Local).AddTicks(8724),
                            MinimumHeight = 600,
                            MinimumWidth = 800,
                            Name = "Sample Title Sign",
                            RatioHeight = 9,
                            RatioWidth = 16,
                            SignType = 2,
                            TwitterHandle = "",
                            Url = "oleary"
                        },
                        new
                        {
                            Id = -3,
                            College = 1,
                            Description = "Sample sign used for testing",
                            IsActive = true,
                            LastUpdated = new DateTime(2022, 3, 17, 11, 35, 43, 708, DateTimeKind.Local).AddTicks(8829),
                            MinimumHeight = 600,
                            MinimumWidth = 800,
                            Name = "Sample Image Sign",
                            RatioHeight = 9,
                            RatioWidth = 16,
                            SignType = 1,
                            TwitterHandle = "",
                            Url = "gies1055"
                        },
                        new
                        {
                            Id = -4,
                            College = 1,
                            Description = "Sample sign used for testing",
                            IsActive = true,
                            LastUpdated = new DateTime(2022, 3, 17, 11, 35, 43, 708, DateTimeKind.Local).AddTicks(8834),
                            MinimumHeight = 600,
                            MinimumWidth = 800,
                            Name = "Sample Image Sign #2",
                            RatioHeight = 9,
                            RatioWidth = 16,
                            SignType = 1,
                            TwitterHandle = "",
                            Url = "gies1041"
                        });
                });

            modelBuilder.Entity("DigitalSignEditor.Data.Models.SignPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SignId");

                    b.ToTable("SignPermissions");
                });

            modelBuilder.Entity("DigitalSignEditor.Data.Models.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Option")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SignId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StorageItemId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SignId");

                    b.ToTable("Slides");
                });

            modelBuilder.Entity("DigitalSignEditor.Data.Models.StorageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StorageItems");
                });

            modelBuilder.Entity("DigitalSignEditor.Data.Models.SignPermission", b =>
                {
                    b.HasOne("DigitalSignEditor.Data.Models.Sign", "Sign")
                        .WithMany("SignPermissions")
                        .HasForeignKey("SignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sign");
                });

            modelBuilder.Entity("DigitalSignEditor.Data.Models.Slide", b =>
                {
                    b.HasOne("DigitalSignEditor.Data.Models.Sign", "Sign")
                        .WithMany("Slides")
                        .HasForeignKey("SignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sign");
                });

            modelBuilder.Entity("DigitalSignEditor.Data.Models.Sign", b =>
                {
                    b.Navigation("SignPermissions");

                    b.Navigation("Slides");
                });
#pragma warning restore 612, 618
        }
    }
}
